<%@ Page Title="User Info" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="User_Info.aspx.cs" Inherits="NestHub_BackEnd.User_Info" %>
<asp:Content ID="Content1" ContentPlaceHolderID="content_body" runat="server">
    <div class = "container">
        <div class="gridview-container">
            <asp:GridView ID="GridView1" runat="server" CssClass="gridview" AutoGenerateDeleteButton="True" OnRowDeleting="UserDeleting_Event" DataKeyNames="UserID" AutoGenerateSelectButton="True" OnSelectedIndexChanging="UserSelecting_Event">
            </asp:GridView>
            <asp:GridView ID="GridView2" runat="server" CssClass="gridview" AutoGenerateDeleteButton="True" DataKeyNames="PropID" OnRowDeleting="ListingDeleting_Event">
            </asp:GridView>
        </div>
    </div>
</asp:Content>
